name: Compile Repository Content

on:
  permissions:
    contents: write
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Fetch wiki
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git wiki
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
    
    - name: Compile content
      run: |
        mkdir -p GenerativeAI
        python .github/scripts/compile_content.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add GenerativeAI/compiled_content.md
        git commit -m "Update compiled content" || echo "No changes to commit"
        git push
